# Intermediate Python: Programming

# Class 3

By the end of this class, you should be able to:

- identify and correct different types of errors as reported by python
- test and validate complex functions
- include help documentation within a function
- define defaults for a function

## Errors and Exceptions

Take look at the following code. 
What happens when you execute it?

```
def favorite_ice_cream():
    ice_creams = [
        "chocolate",
        "vanilla",
        "strawberry"
    ]
    print(ice_creams[3])

favorite_ice_cream()
```

interpreting traceback:

- determine number of levels by looking for arrows on lefthand side
- first arrow points to line 8, favorite_ice_cream()
- second arrow shows code within function, line 6
- last level shown is where error occurred
- most of the time you can pay attention to last level!

There are three main types of errors you'll see reported from Python:

In [ ]:
## Syntax errors

# error from defining a function incorrectly
def some_function()
    msg = "hello, world!"
    print(msg)
     return msg
# colon error: add colon to first line
def some_function():
    msg = "hello, world!"
    print(msg)
     return msg
# another error! IntentationError is a type of syntax, but is always about indentation
# correct indentation:
def some_function():
    msg = "hello, world!"
    print(msg)
    return msg
# whitespace: tabs and spaces
# many interpreters correct spaces meant to be tabs, but python doesn't allow you to mix!

In [1]:
## Variable name errors

# try to print a variable
print(octopus)
# NameErrors can be difficult to fix
# common problem is that it's not a variable, but a string you forgot to place quotations around
print("octopus")
# another problem: forgot to create variable before using it:
#count = 0 # add this to fix it
for number in range(10):
    count = count + number
print("The count is:", count)
# if you accidentally include Count = 0 instead, this will also give variable name error!

NameError: name 'octopus' is not defined

In [ ]:
## Index errors
# accessing an item in a container that doesn't exist
letters = ['a', 'b', 'c']
print("Letter #1 is", letters[0])
print("Letter #2 is", letters[1])
print("Letter #3 is", letters[2])
print("Letter #4 is", letters[3])

In [ ]:
## File errors

# trying to read a file that doesn't exist, or is in a different location
file_handle = open('myfile.txt')
file_handle = open("inflammation-01.csv", 'r')
# attempt to write to a file that was opened read-only: UnsupportedOperationError
# also IOErrors or OSErrors, depending on the version of Python

In [ ]:
## Challenge:
# This code has an intentional error. Do not type it directly;
# use it for reference to understand the error message below.
def print_message(day):
    messages = {
        "monday": "Hello, world!",
        "tuesday": "Today is tuesday!",
        "wednesday": "It is the middle of the week.",
        "thursday": "Today is Donnerstag in German!",
        "friday": "Last day of the week!",
        "saturday": "Hooray for the weekend!",
        "sunday": "Aw, the weekend is almost over."
    }
    print(messages[day])

def print_friday_message():
    print_message("Friday")

print_friday_message()

## Testing and documenting

validating that a function works as expected is an important step in coding
this section creates a new function that manipulates the data
difference between testing (verification) and validating:
testing/verifying: does code do what we expect?
validating: does code meet our need (stated goal)?

In [2]:
import numpy

In [3]:
# write a function to offset data by a new user-selected mean value
def offset_mean(data, target_mean_value):
    return (data - numpy.mean(data)) + target_mean_value

In [4]:
# create test matrix of 0s
z = numpy.zeros((2,2))
print(z)
# offset values using new function
print(offset_mean(z, 3))


[[0. 0.]
 [0. 0.]]
[[3. 3.]
 [3. 3.]]


In [5]:
# use offset function on real data
data = numpy.loadtxt(fname="data/inflammation-01.csv", delimiter=",")
print(offset_mean(data, 0))


[[-6.14875 -6.14875 -5.14875 ... -3.14875 -6.14875 -6.14875]
 [-6.14875 -5.14875 -4.14875 ... -5.14875 -6.14875 -5.14875]
 [-6.14875 -5.14875 -5.14875 ... -4.14875 -5.14875 -5.14875]
 ...
 [-6.14875 -5.14875 -5.14875 ... -5.14875 -5.14875 -5.14875]
 [-6.14875 -6.14875 -6.14875 ... -6.14875 -4.14875 -6.14875]
 [-6.14875 -6.14875 -5.14875 ... -5.14875 -5.14875 -6.14875]]


In [6]:
# confirm offset has worked
print('original min, mean, and max are:', numpy.min(data), numpy.mean(data), numpy.max(data))
offset_data = offset_mean(data, 0)
print('min, mean, and max of offset data are:',
      numpy.min(offset_data),
      numpy.mean(offset_data),
      numpy.max(offset_data))
# offset isn't exact, but is close


original min, mean, and max are: 0.0 6.14875 20.0
min, mean, and max of offset data are: -6.14875 2.842170943040401e-16 13.85125


In [8]:
# check standard deviation
print('std dev before and after:', numpy.std(data), numpy.std(offset_data))
# check more precisely
print('difference in standard deviations before and after:',
      numpy.std(data) - numpy.std(offset_data))

std dev before and after: 4.613833197118566 4.613833197118566
difference in standard deviations before and after: 0.0


we could add documentation to offset function to describe its purpose using comments:
```
# offset_mean(data, target_mean_value)
# return a new array containing the original data with its mean offset to match the desired value.
def offset_mean(data, target_mean_value):
    return (data - numpy.mean(data)) + target_mean_value
```

In [10]:
# a better way: add string to function itself, which embeds in help documentation
def offset_mean(data, target_mean_value):
    '''Return a new array containing the original data
       with its mean offset to match the desired value.'''
    return (data - numpy.mean(data)) + target_mean_value
# view help documentation
help(offset_mean)


In [11]:
# docstring; triple quotes aren't necessary, but allow us to break into separate lines (and add example)
def offset_mean(data, target_mean_value):
    '''Return a new array containing the original data
       with its mean offset to match the desired value.
    Example: offset_mean([1, 2, 3], 0) => [-1, 0, 1]'''
    return (data - numpy.mean(data)) + target_mean_value
help(offset_mean)

Help on function offset_mean in module __main__:

offset_mean(data, target_mean_value)
    Return a new array containing the original data
       with its mean offset to match the desired value.
    Example: offset_mean([1, 2, 3], 0) => [-1, 0, 1]



Challenge: given the following function (written in last week's class), add a docstring
```
def fahr_to_celsius(temp):
    return ((temp - 32) * (5/9))
```

## Defining defaults

In [14]:
# pass the filename to loadtxt without the fname=
#numpy.loadtxt(fname="data/inflammation-01.csv", delimiter=",")
#numpy.loadtxt("data/inflammation-01.csv", delimiter=",")
# delimiter needs to be there! this gives an error:
numpy.loadtxt("data/inflammation-01.csv", ",")

SyntaxError: unexpected EOF while parsing (<string>, line 1)

In [15]:
# redefine offset mean, which makes the default 0.0
def offset_mean(data, target_mean_value=0.0):
    '''Return a new array containing the original data with its mean offset to match the
       desired value (0 by default).
    Example: offset_mean([1, 2, 3], 0) => [-1, 0, 1]'''
    return (data - numpy.mean(data)) + target_mean_value


In [16]:
# can still call function with two arguments
test_data = numpy.zeros((2, 2))
print(offset_mean(test_data, 3))


[[3. 3.]
 [3. 3.]]


In [17]:
# call it with just one parameter, target_mean_value automatically assigned the default value of 0.0
more_data = 5 + numpy.zeros((2, 2))
print('data before mean offset:', more_data)
print('offset data:', offset_mean(more_data))


data before mean offset: [[5. 5.]
 [5. 5.]]
offset data: [[0. 0.]
 [0. 0.]]


In [18]:
# how Python matches values to parameters:
def display(a=1, b=2, c=3):
    print('a:', a, 'b:', b, 'c:', c)

print('no parameters:')
display()
print('one parameter:')
display(55)
print('two parameters:')
display(55, 66)

no parameters:
a: 1 b: 2 c: 3
one parameter:
a: 55 b: 2 c: 3
two parameters:
a: 55 b: 66 c: 3


In [19]:
# parameters are matched left to right
# any without value given by user automatically get default value


In [20]:
# override behavior by naming value as it's passed (entered)
print('only setting the value of c')
display(c=77)

only setting the value of c
a: 1 b: 2 c: 77


In [21]:
# interpreting help documentation: example from numpy.loadtxt
help(numpy.loadtxt)
# loadtxt has one parameter called fname that doesn’t have a default value, and eight others that do
# numpy.loadtxt('inflammation-01.csv', ',')
# doesn't work because delimiter isn't the second argument in the help doc, so the function assigns the wrong default argument


Help on function loadtxt in module numpy.lib.npyio:

loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes')
    Load data from a text file.
    
    Each row in the text file must have the same number of values.
    
    Parameters
    ----------
    fname : file, str, or pathlib.Path
        File, filename, or generator to read.  If the filename extension is
        ``.gz`` or ``.bz2``, the file is first decompressed. Note that
        generators should return byte strings for Python 3k.
    dtype : data-type, optional
        Data-type of the resulting array; default: float.  If this is a
        structured data-type, the resulting array will be 1-dimensional, and
        each row will be interpreted as an element of the array.  In this
        case, the number of columns used must match the number of fields in
        the data-type.
    comments : str or sequence of str, optional
       

In [22]:
## Challenge: given the following code, what do you expect to be written? Run it to confirm your answer
def numbers(one, two=2, three, four=4):
    n = str(one) + str(two) + str(three) + str(four)
    return n

print(numbers(1, three=3))


SyntaxError: non-default argument follows default argument (<ipython-input-22-2f576c09a07f>, line 2)

In [23]:
## Challenge: what does the following code display when run?
def func(a, b=3, c=6):
    print('a: ', a, 'b: ', b, 'c:', c)

func(-1, 2)


a:  -1 b:  2 c: 6
